[features]
seeds = false
skip-lint = false
[programs.localnet]
anchor_test = "5nW66C8SHfsfUBbsAm9bRcbpn9tLHESjFSaJUTyGrjsF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = ""

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
